### ISSUE TITLE
Read credentials from ~/.aws/credentials when available

### ISSUE THREAD

**Issue by benmccann** [rossf7/elasticrawl#12]
If you run `aws configure` it stores your credentials in `~/.aws/credentials`. It would be nice for elasticrawl to read the credentials from there instead of asking for them

**Comment by rossf7** [comment]
Hi Ben,
thanks for raising this. Yes currently elasticrawl checks for the environment variables AWS_ACCESS_KEY_ID or AWS_SECRET_ACCESS_KEY. If these don't exist it prompts for them.

It makes sense to check ~/.aws/credentials too since it's used by the AWS CLI. I'll have a look at this when I can this should be in the next couple of weeks.

Cheers

Ross

**Comment by rossf7** [comment]
Both this issue and the project are stale. Closing.
